import streamlit as st
import pickle

# Configure browser tab
st.set_page_config(
    page_title="Job Fraud Detector",
    page_icon="🛡️",
    layout="centered"
)

# Load model
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

# Load TF-IDF
with open("tfidf.pkl", "rb") as f:
    tfidf = pickle.load(f)

st.title("🛡️ Job Fraud Detector")
st.caption("Detect whether a job posting is legitimate or fraudulent using Machine Learning.")


job_text = st.text_area(
    "Enter Job Post : ",
    placeholder="Paste the complete job description, including company details, responsibilities, and requirements...",
    height=250
)

if st.button("🔍 Analyze Content", use_container_width=True):

    if not job_text.strip():
        st.warning("Please enter a job post.")

    elif len(job_text.split()) < 10:
        st.warning("Please enter at least 10 words.")

    else:
        text_tfidf = tfidf.transform([job_text])
        prediction = model.predict(text_tfidf)

        if prediction[0] == 0:
            st.success("✅ Legitimate Job Posting")
            st.info("The submitted job posting appears to be genuine based on the trained Machine Learning model.")

        else:
            st.error("⚠️ Fraudulent Job Posting")
            st.warning(
                "This job posting shows characteristics commonly associated with fraudulent advertisements. "
                "Please verify the employer before applying."
            )
            
st.markdown(
    "**Disclaimer:** This prediction is generated by a Machine Learning model and may not always be accurate. Always verify the employer before applying."
)