import streamlit as st
import pickle
import pdfplumber

# Configure browser tab
st.set_page_config(
    page_title="Job Fraud Detector",
    page_icon="🛡️",
    layout="centered"
)

# Load model
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

# Load TF-IDF
with open("tfidf.pkl", "rb") as f:
    tfidf = pickle.load(f)

st.title("🛡️ Job Fraud Detector")
st.caption("Detect whether a job posting is legitimate or fraudulent using Machine Learning.")

# Function for extration text from pdf

def extract_text_pdf(uploaded_pdf):
    
    with pdfplumber.open(uploaded_pdf) as pdf:
        
        text_part = []
        
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text_part.append(page_text)
        return "\n".join(text_part)
    
# Radio for text and pdf

input_mode = st.radio("Choose input Method : ", ['✏️ Paste Text', '📄 Upload PDF'], horizontal=True)

# Empty string
job_text = ""

if input_mode == '✏️ Paste Text':
    job_text = st.text_area(
    "Enter Job Post : ",
    placeholder="Paste the complete job description, including company details, responsibilities, and requirements...",
    height=250
    )

else:
    
    uploaded_pdf_file = st.file_uploader('📤 Upload your job posting PDF file', type=['pdf'])
    
    if uploaded_pdf_file is not None:
        
        with st.spinner("Extracting text from PDF...."):
            
            try:
                
                job_text = extract_text_pdf(uploaded_pdf_file)
                
            except Exception as e:
                
                st.error(f"🔴 Could not read PDF file {e}")
                job_text = ""
                
        if job_text.strip():
            
            st.success("✅ Text extraction completed Successfully!")
            with st.expander("📄 View extracted text from PDF"):
                st.text_area("🗎 Extracted content : ", value=job_text, height=250)
        else:
            st.warning("⚠️ No readable text found in this PDF. It may be a scanned/image-based PDF.")

if st.button("🔍 Analyze Content", use_container_width=True):

    if not job_text.strip():
        st.warning("🚨 Please enter a job post.")

    elif len(job_text.split()) < 10:
        st.warning("🚨 Please enter at least 10 words.")

    else:
        text_tfidf = tfidf.transform([job_text])
        prediction = model.predict(text_tfidf)

        if prediction[0] == 0:
            st.success("✅ Legitimate Job Posting")
            st.info("The submitted job posting appears to be genuine based on the trained Machine Learning model.")

        else:
            st.error("⚠️ Fraudulent Job Posting")
            st.warning(
                "This job posting shows characteristics commonly associated with fraudulent advertisements. "
                "Please verify the employer before applying."
            )
            
st.markdown(
    "📢 **Disclaimer:** This prediction is generated by a Machine Learning model and may not always be accurate. Always verify the employer before applying."
)
